<div class="min-h-screen bg-gradient-to-br from-purple-600 to-blue-600 py-12 px-4">
    <div class="max-w-4xl mx-auto">
        <!-- Header -->
        <div class="flex items-center justify-between mb-8">
            <a href="{{ route('portfolio.index') }}" class="inline-flex items-center px-4 py-2 bg-white text-gray-900 rounded-lg hover:bg-gray-100 transition font-medium">
                ← Back
            </a>
            <button onclick="window.print()" class="inline-flex items-center px-4 py-2 bg-white text-gray-900 rounded-lg hover:bg-gray-100 transition font-medium">
                🖨️ Print
            </button>
        </div>

        <!-- Document -->
        <div class="bg-white rounded-lg shadow-2xl p-12">
            <div class="mb-12 border-b-2 border-gray-200 pb-8">
                <h1 class="text-4xl font-bold text-gray-900 mb-2">{{ $title }}</h1>
                @if ($document->evaluation)
                    <p class="text-gray-600 text-lg">
                        <strong>{{ $document->evaluation->company }}</strong> • {{ $document->evaluation->position }}
                    </p>
                @endif
            </div>

            <!-- Content (HTML rendered) -->
            <div class="prose prose-lg max-w-none text-gray-700">
                {!! $document->toHtml() !!}
            </div>

            <!-- Footer -->
            <div class="mt-16 pt-8 border-t border-gray-200 text-center text-sm text-gray-500">
                <p>Document generated by Career-Ops</p>
                <p class="mt-1">{{ $document->created_at->format('M d, Y') }}</p>
            </div>
        </div>
    </div>

    <style>
        @media print {
            body {
                background: white;
            }
            .prose {
                color: black;
            }
            a {
                color: #0066cc;
            }
        }
    </style>
</div>
